---
 
- hosts: all
  become: true
  tasks:
 
 
  - name: install apache2 package on Ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd package on AlmaLinux
    dnf:
      name:
      - httpd
      - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"
